;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2023 Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 5D87CC3D482974F3F631B48C0940C3ACD87812E95C23EF84C3490CF99189058F
; Input MD5    : ACDDD7555614FFE2E6484582F886B87C
; Input CRC32  : 70AFC07B
; Processor       : z80 []
; Target assembler: Zilog Macro Assembler
; ===========================================================================
; Segment type: Pure code
; Main segment
; =============== S U B R O U T I N E =======================================

YM2612_A0 EQU $4000
YM2612_D0 EQU $4001
PCM_ID EQU $017F
STACK EQU $1FFF

start:
                di
                ld      sp, STACK

loc_4:                                  ; CODE XREF: start+8↓j
                                        ; start+1F↓j ...
                ld      a, (PCM_ID)
                or      a
                jp      z, loc_4
                cp      1
                jp      z, loc_68
                cp      2
                jp      z, loc_76
                cp      3
                jp      z, loc_84
                cp      4
                jp      z, loc_92
                jp      loc_4
; ---------------------------------------------------------------------------
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                reti
; ---------------------------------------------------------------------------
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                retn
; ---------------------------------------------------------------------------

loc_68:                                 ; CODE XREF: start+D↑j
                ld      hl, pcm_audio
                ld      bc, pcm_audio_end-pcm_audio
                ld      a, 50h ; 'P'
                ld      ($1D0F), a
                jp      loc_A0
; ---------------------------------------------------------------------------

loc_76:                                 ; CODE XREF: start+12↑j
                ld      hl, pcm_audio
                ld      bc, pcm_audio_end-pcm_audio
                ld      a, 68h ; 'h'
                ld      ($1D0F), a
                jp      loc_A0
; ---------------------------------------------------------------------------

loc_84:                                 ; CODE XREF: start+17↑j
                ld      hl, pcm_audio
                ld      bc, pcm_audio_end-pcm_audio
                ld      a, 80h
                ld      ($1D0F), a
                jp      loc_A0
; ---------------------------------------------------------------------------

loc_92:                                 ; CODE XREF: start+1C↑j
                ld      hl, pcm_audio
                ld      bc, pcm_audio_end-pcm_audio
                ld      a, 98h
                ld      ($1D0F), a
                jp      loc_A0
; ---------------------------------------------------------------------------

loc_A0:                                 ; CODE XREF: start+73↑j
                                        ; start+81↑j ...
                call    sub_DD
                push    bc
                ld      a, 80h
                ld      c, 2Bh ; '+'
                call    sub_D2
                pop     bc
                ld      a, ($1D0F)

loc_AF:                                 ; CODE XREF: start+C4↓j
                push    bc
                ld      b, a

loc_B1:                                 ; CODE XREF: start:loc_B1↓j
                djnz    $
                pop     bc
                push    af
                push    bc
                ld      a, (hl)
                ld      c, 2Ah ; '*'
                call    sub_D2
                pop     bc
                inc     hl
                dec     bc
                ld      a, b
                or      c
                jr      z, loc_C6
                pop     af
                jr      loc_AF
; ---------------------------------------------------------------------------

loc_C6:                                 ; CODE XREF: start+C1↑j
                xor     a
                ld      (PCM_ID), a
                ld      c, 2Bh ; '+'
                call    sub_D2
                jp      loc_4
; End of function start


; =============== S U B R O U T I N E =======================================


sub_D2:                                 ; CODE XREF: start+A8↑p
                                        ; start+B9↑p ...
                push    af
                ld      a, c
                ld      (YM2612_A0), a
                pop     af
                nop
                ld      (YM2612_D0), a
                ret
; End of function sub_D2


; =============== S U B R O U T I N E =======================================


sub_DD:                                 ; CODE XREF: start:loc_A0↑p
                push    hl
                push    de
                push    bc
                ld      b, 7
                xor     a
                ld      c, 28h ; '('

loc_E5:                                 ; CODE XREF: sub_DD+C↓j
                call    sub_D2
                inc     a
                djnz    loc_E5
                pop     bc
                pop     de
                pop     hl
                ret
; End of function sub_DD

; ---------------------------------------------------------------------------
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
                nop
byte_17F:       db 0                    ; DATA XREF: start:loc_4↑r
                                        ; start+C7↑w
pcm_audio:                              ; DATA XREF: start:loc_68↑o
                                        ; start:loc_76↑o ...
                INCBIN "audio/pcm/000173B4.pcm"
pcm_audio_end:
