name: ci
run-name: Building Sega Genesis ROM
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
          architecture: windows/amd64
      - name: Prepare
        run: |
          rm -r -Fo screenshots/*
          mkdir build
          echo "" > '${{github.workspace}}\build\Altered Beast (US).bin'
          echo "" > '${{github.workspace}}\build\Altered Beast (US).txt'
      - name: Execute asm68k
        run: |
          $GHWORKSPACE="${{ github.workspace }}"
          $GHWORKSPACE=$GHWORKSPACE.replace("\", "/")
          make WORKSPACE="$GHWORKSPACE" NAME="Altered Beast" VERSION="US" ASM68K_SWITCHES="//m //p //k" build
      - name: Run Blastem and record movie
        run: |
          ${{github.workspace}}\tools\RetroArch-Win64\retroarch.exe -L "${{github.workspace}}\tools\RetroArch-Win64\cores\blastem_libretro.dll" "${{github.workspace}}\build\Altered Beast (US).bin" --record="${{github.workspace}}\screenshots\blastem.mkv" --appendconfig="${{github.workspace}}\retroarch.cfg" --max-frames=10000 --verbose 
      - name: Run Genesis Plus GX and record movie
        run: |
          ${{github.workspace}}\tools\RetroArch-Win64\retroarch.exe -L "${{github.workspace}}\tools\RetroArch-Win64\cores\genesis_plus_gx_libretro.dll" "${{github.workspace}}\build\Altered Beast (US).bin" --record="${{github.workspace}}\screenshots\gensplusgx.mkv" --appendconfig="${{github.workspace}}\retroarch.cfg" --max-frames=2600 --verbose
      - name: Run Picodrive and record movie
        run: |
          ${{github.workspace}}\tools\RetroArch-Win64\retroarch.exe -L "${{github.workspace}}\tools\RetroArch-Win64\cores\picodrive_libretro.dll" "${{github.workspace}}\build\Altered Beast (US).bin" --record="${{github.workspace}}\screenshots\picodrive.mkv" --appendconfig="${{github.workspace}}\retroarch.cfg" --max-frames=2600 --verbose
      - name: GIT Commit Build Records
        if: github.event_name == 'push'
        run: |
          git config --global user.name "Hans Bonini"
          git config --global user.email "hans@ysolutions.com.br"
          git add screenshots screenshots/blastem.png
          git commit -m "Adding screenshots from build ${{ github.sha }}"
          git push