name: build-sega-genesis-asm-action
run-name: ${{ github.actor }} is building Sega Genesis assembler code
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
          architecture: windows/amd64
      - name: Create Build Directory
        run: mkdir ${{ github.workspace }}/build
      - name: Execute asm68k
        run: make WORKSPACE=${{ github.workspace }} build
          
