name: build
run-name: Building Sega Genesis ROM
on:
  push:
    branches: [ master ]
jobs:
  ue_rev02:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
          architecture: windows/amd64
      - name: Prepare Build
        run: |
          mkdir build
          "" | Out-File -LiteralPath "${{github.workspace}}\build\Altered Beast (UE) (REV02) [!].bin"
          "" | Out-File -LiteralPath "${{github.workspace}}\build\Altered Beast (UE) (REV02) [!].txt"
      - name: Create Screenshots directory
        id: createscreenshotsdir
        run: |
          Remove-Item "${{github.workspace}}\screenshots" -Recurse -ErrorAction Ignore
          mkdir screenshots
      - name: Execute asm68k
        run: |
          $GHWORKSPACE="${{ github.workspace }}"
          $GHWORKSPACE=$GHWORKSPACE.replace("\", "/")
          make WORKSPACE="$GHWORKSPACE" NAME="Altered Beast" REGION="UE" VERSION=REV02 ASM68K_SWITCHES="//m //p //k" build