name: ci
run-name: Building Sega Genesis ROM
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
          architecture: windows/amd64
      - name: Prepare Build
        run: |
          mkdir build
          echo "" > "${{github.workspace}}\build\Altered Beast (UE) (REV02) [!].bin"
          echo "" > "${{github.workspace}}\build\Altered Beast (UE) (REV02) [!].txt"
      - name: Create Screenshots directory
        id: createscreenshotsdir
        run: |
          Remove-Item "${{github.workspace}}\screenshots" -Recurse -ErrorAction Ignore
          mkdir screenshots
      - name: Execute asm68k
        run: |
          $GHWORKSPACE="${{ github.workspace }}"
          $GHWORKSPACE=$GHWORKSPACE.replace("\", "/")
          make WORKSPACE="$GHWORKSPACE" NAME="Altered Beast" REGION="UE" VERSION=REV02 ASM68K_SWITCHES="//m //p //k" build
      - name: Run Picodrive and record movie
        run: |
          Invoke-Expression '${{github.workspace}}\tools\RetroArch-Win64\retroarch.exe -L "${{github.workspace}}\tools\RetroArch-Win64\cores\picodrive_libretro.dll" --appendconfig="${{github.workspace}}\retroarch.cfg" --record="${{github.workspace}}\screenshots\picodrive.gif" --max-frames=2600 "${{github.workspace}}\build\Altered Beast (UE) (REV02) [!].bin" --verbose' -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 20
      - name: Run Genesis Plus Gx and record movie
        run: |
          Invoke-Expression '${{github.workspace}}\tools\RetroArch-Win64\retroarch.exe -L "${{github.workspace}}\tools\RetroArch-Win64\cores\genesis_plus_gx_libretro.dll" --appendconfig="${{github.workspace}}\retroarch.cfg" --record="${{github.workspace}}\screenshots\genesisplusgx.gif" --max-frames=2600 "${{github.workspace}}\build\Altered Beast (UE) (REV02) [!].bin" --verbose' -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 20
      - name: Run Blastem and record movie
        run: |
          Invoke-Expression '${{github.workspace}}\tools\RetroArch-Win64\retroarch.exe -L "${{github.workspace}}\tools\RetroArch-Win64\cores\blastem_libretro.dll" --appendconfig="${{github.workspace}}\retroarch.cfg" --record="${{github.workspace}}\screenshots\blastem.gif" --max-frames=2600 "${{github.workspace}}\build\Altered Beast (UE) (REV02) [!].bin" --verbose' -ErrorAction SilentlyContinue
          Start-Sleep -Seconds 20
      - name: GIT Commit Build Records
        if: github.event_name == 'push'
        run: |
          git config --global user.name "Hans Bonini"
          git config --global user.email "hans@ysolutions.com.br"
          git add screenshots screenshots/\*
          git commit -m "Adding screenshots from build ${{ github.sha }}"
          git push