name: build-sega-genesis-asm-action
run-name: ${{ github.actor }} is building Sega Genesis assembler code
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
          architecture: windows/amd64
      - name: Create list file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "build/Altered Beast US_list.txt"
          FILE_DATA: ""
      - name: Create ROM file
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "build/Altered Beast (US).bin"
          FILE_DATA: ""
      - name: Execute asm68k
        run: |
          make build
          
          
