name: picodrive
run-name: Building Sega Genesis ROM and Test on Picodrive
on:
  push:
    branches: [ master ]
jobs:
  test-ue-rev02:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
        with:
          # Target architecture for Go to use. Examples: x86, x64. Will use system architecture by default.
          architecture: windows/amd64
      - name: Prepare Build
        run: |
          New-Item -Path "${{github.workspace}}\build" -ItemType Directory -ErrorAction Ignore
          "" | Out-File -LiteralPath "${{github.workspace}}\build\Altered Beast (UE) (REV02) [!].bin"
          "" | Out-File -LiteralPath "${{github.workspace}}\build\Altered Beast (UE) (REV02) [!].txt"
      - name: Create Screenshots directory
        id: createscreenshotsdir
        run: |
          New-Item -Path "${{github.workspace}}\screenshots" -ItemType Directory -ErrorAction Ignore
      - name: Execute asm68k
        run: |
          $GHWORKSPACE="${{ github.workspace }}"
          $GHWORKSPACE=$GHWORKSPACE.replace("\", "/")
          make WORKSPACE="$GHWORKSPACE" NAME="Altered Beast" REGION="UE" VERSION=REV02 ASM68K_SWITCHES="//m //p //k" build
      - name: Run Picodrive and record movie
        run: |
            Invoke-Expression '${{github.workspace}}\tools\RetroArch-Win64\retroarch.exe -L "${{github.workspace}}\tools\RetroArch-Win64\cores\picodrive_libretro.dll" --appendconfig="${{github.workspace}}\retroarch.cfg" --record="${{github.workspace}}\screenshots\picodrive.gif" --max-frames=2400 "${{github.workspace}}\build\Altered Beast (UE) (REV02) `[!`].bin" --verbose' -ErrorAction SilentlyContinue
            Start-Sleep -Seconds 180
      - name: GIT Commit Build Records
        if: github.event_name == 'push'
        run: |
          git config --global user.name "Hans Bonini"
          git config --global user.email "hans@ysolutions.com.br"
          git add screenshots screenshots/\*
          git pull
          git commit -m "Adding picodrive screenshots from test build ${{ github.sha }}"
          git push